
name: Deploy Python App to GHCR

on:
  push:
    branches:
      - main

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout GitHub Actions'
        uses: actions/checkout@v2.18.2

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build Python Image'
        run: |
          docker build . -t ghcr.io/${{ github.repository_owner }}/python-app:latest

      - name: 'Push Python Image to GHCR'
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/python-app:latest
